### ISSUE TITLE
Webview 에서 로그인 불가

### ISSUE THREAD

**Issue by sunjae-kim** [zzulu/zzu-li#1]
카카오톡 등 모바일 플랫폼에서 로그인 시도 시 `disallowed_useragent` 에러가 발생합니다.

![KakaoTalk_Photo_2019-09-10-21-29-42](https://user-images.githubusercontent.com/40228715/64614010-7e00eb00-d412-11e9-811e-5e7a71a1b56d.jpeg)

**Comment by sunjae-kim** [comment]
https://developers-kr.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

Google 에서 WebView 를 통한 로그인을 허용하지 않고 있어서 이슈는 close 하겠습니다.

**Comment by zzulu** [comment]
webview일 경우, 다른 브라우저로 보내거나 하는 등의 처리가 필요하겠군요!
